<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductDetailsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('product_details')->truncate();

        DB::unprepared(<<<'SQL'
INSERT INTO `product_details` (`product_detail_id`, `product_id`, `sample_image`, `specification_image`, `detail_content`, `specification_content`, `accordion_content`, `is_active`, `created_at`, `updated_at`) VALUES
(1, 1, 'products/details/VTYAHJg5qkcXJuhM28TU6rOeeYvfnXBI1NO4dQ8T.png', 'products/specifications/E3jDKxMpQne44cgFc9i5KBlLUJqX7AfX1Omx3kKK.png', '[{\"headline\":\"Cuidado em cada detalhe\",\"desc\":\"Qualidade rigorosa do material \\u00e0 impress\\u00e3o final.\",\"icon_image\":\"products\\/detail-icons\\/JT55Y6bFfXgdpUkvSxVmYjJb90TH20aW4tMYnAF7.png\"},{\"headline\":\"Suporte do in\\u00edcio ao fim\",\"desc\":\"Aux\\u00edlio personalizado do design \\u00e0 entrega.\",\"icon_image\":\"products\\/detail-icons\\/IvAz4BZiplFAkUGwTDXQguibJvQTV1DNvW7uEFYz.png\"},{\"headline\":\"Garantia de Satisfa\\u00e7\\u00e3o\",\"desc\":\"Compromisso total com o resultado esperado.\",\"icon_image\":\"products\\/detail-icons\\/HLVtl7o6gTQrx0oOJGb2Tydbt6ovdufpDEHcYM12.png\"},{\"headline\":\"Custo-benef\\u00edcio Real\",\"desc\":\"Qualidade premium com o melhor pre\\u00e7o.\",\"icon_image\":null}]', '[{\"title\":\"Width Options:\",\"desc\":\"10mm, 15mm, 20mm, and more\",\"link_text\":null,\"link_url\":null,\"icon_image\":\"products\\/spec-icons\\/uGdgHOkxVbyxgaAJfIzJaSYz4BoUz1W2h4XdXQ0t.png\"},{\"title\":\"Color:\",\"desc\":\"Pantone 485C\",\"link_text\":\"(View more colors)\",\"link_url\":\"https:\\/\\/master-brindes.jp\\/products\\/1\\/description\",\"icon_image\":\"products\\/spec-icons\\/qk3z3NLDDSTkMTBhumrme7meyrQ4h1iK9tWkrEmv.png\"},{\"title\":\"Attachments:\",\"desc\":\"Multiple options available\",\"link_text\":null,\"link_url\":null,\"icon_image\":\"products\\/spec-icons\\/Jn8l4QBRpTSzgJhkCy2G2TrnSjutLQtdR6MURsmJ.png\"},{\"title\":\"Material:\",\"desc\":\"Polyester\",\"link_text\":null,\"link_url\":null,\"icon_image\":\"products\\/spec-icons\\/sa6q152a9Rf14DDbWjzlDWL3FTUB6Yozc6Nq0hQm.png\"},{\"title\":\"Minimum Order Quantity:\",\"desc\":\"20 pieces\",\"link_text\":null,\"link_url\":null,\"icon_image\":\"products\\/spec-icons\\/Ecz1Kb0VRaL6IQINvNCg8Qk0uY38c6d6DFEghXhF.png\"}]', '[{\"title\":\"Production fee\",\"content\":\"<p>Neck strap production cost =<br>\\u2460 Printing plate fee + \\u2461 (Product unit price x quantity)<br>\\u2460 Printing plate fee :&nbsp;4,400\\u2028yen (tax included) per printing color&nbsp;. For two-color printing, the&nbsp;fee is&nbsp;8,800&nbsp;yen (tax included). *If the front and back designs are different for double-sided printing, it will be treated as two colors even if the printing color is the same.<br>\\u2461 For customers checking the unit price of products by order quantity\\u2028on their mobile devices, please slide the price list to view the details<\\/p><p><br>&nbsp;<\\/p>\"}]', 1, '2026-05-06 23:51:35', '2026-05-06 23:58:52'),
(2, 3, 'products/details/D6O21Th9pHdJA2MYe2UUCMH9W2z9Vdqhl1LCEYbE.png', 'products/specifications/TDwMyfvm127MEJylnUbaoIxIKLCnjSk3y0qm9q2c.webp', '[{\"headline\":\"Material Premium\",\"desc\":\"Produzido em acr\\u00edlico de alta resist\\u00eancia com corte a laser preciso, oferecendo transpar\\u00eancia cristalina e bordas lisas.\",\"icon_image\":null},{\"headline\":\"Impress\\u00e3o de Alta Qualidade\",\"desc\":\"Tecnologia de impress\\u00e3o UV que preserva cores vibrantes e detalhes n\\u00edtidos, sendo resistente a riscos e ao desbotamento.\",\"icon_image\":null},{\"headline\":\"Acess\\u00f3rios Dur\\u00e1veis\",\"desc\":\"Acompanha argola e corrente de metal refor\\u00e7ado, garantindo seguran\\u00e7a para suas chaves ou acess\\u00f3rios de uso di\\u00e1rio.\",\"icon_image\":null},{\"headline\":\"Design Vers\\u00e1til\",\"desc\":\"O acabamento leve e elegante torna-o perfeito para uso pessoal em mochilas e estojos, ou como um item promocional de destaque.\",\"icon_image\":null}]', '[{\"title\":\"Material\",\"desc\":\"Acr\\u00edlico fundido (cast) de alta transpar\\u00eancia com espessura de 3mm.\",\"link_text\":null,\"link_url\":null,\"icon_image\":null},{\"title\":\"Tipo de Impress\\u00e3o\",\"desc\":\"Impress\\u00e3o digital UV de alta resolu\\u00e7\\u00e3o (frente e verso dispon\\u00edveis).\",\"link_text\":null,\"link_url\":null,\"icon_image\":null},{\"title\":\"Corte\",\"desc\":\"Acabamento realizado atrav\\u00e9s de corte a laser de alta precis\\u00e3o.\",\"link_text\":null,\"link_url\":null,\"icon_image\":null},{\"title\":\"Tamanho\",\"desc\":\"Dimens\\u00f5es personaliz\\u00e1veis (padr\\u00e3o de 5cm a 7cm, dependendo do design).\",\"link_text\":null,\"link_url\":null,\"icon_image\":null},{\"title\":\"Ferragens\",\"desc\":\"Argola de a\\u00e7o inoxid\\u00e1vel com di\\u00e2metro de 25mm e corrente rotativa.\",\"link_text\":null,\"link_url\":null,\"icon_image\":null},{\"title\":\"Prote\\u00e7\\u00e3o\",\"desc\":\"Pel\\u00edcula pl\\u00e1stica protetora em ambos os lados para evitar riscos durante o transporte.\",\"link_text\":null,\"link_url\":null,\"icon_image\":null}]', '[{\"title\":null,\"content\":null}]', 1, '2026-05-08 00:25:15', '2026-05-12 19:11:51');
SQL);
    }
}
